### ISSUE TITLE
[FEAT/XML] 1주차 심화과제

### ISSUE THREAD

**Issue by SYAAINN** [NOW-SOPT-ANDROID/minjae-son-new#5]
## 💡 Issue

- [ ] Activity 생명주기 알아보기
- [ ] ViewModel을 사용하여 State 관리해보기
- [ ] UX 고려하여 기능 추가해보기

## 📝 todo

- Activiy 생명주기 알아보기
  - Activity의 생명주기에는 어떤 것이 있고, 각 생명주기에는 어떤 로직을 실행하는가?
  - 생명주기 측면에서 어떠한 것들을 고려해야 할까? `ex) 화면 전환, 다크 모드`
  - [공식문서 링크](https://developer.android.com/guide/components/activities/activity-lifecycle)

- ViewModel을 사용하여 State 관리해보기
  - MVVM 패턴은 무엇이며, 어떤 상황에서 왜 사용하는가?
  - ViewModel은 무엇인가?
  - 관리한다는 State는 무엇인가?
  - View(Activity)의 책임을 덜어보자

- UX 고려하여 기능 추가해보기
   - 뒤로가기 버튼 조정 
     : 현재 메인에서 뒤로가기 누르면 로그인 화면이 뜨는데, 앱 종료로 조정
     : `Intent Flags`, `Activity Task`
   - 텍스트 입력 시 2줄 방지
     : EditText(XML), TextFiled(Compose)의  특정 속성을 활용해 Text를 한 줄로 제한
     : 또한 엔터키를 누르면 다음 입력칸으로 넘어가도록 진행
   - 키보드가 올라올 때 버튼을 가리는 문제
     : 키보드가 올라오면 버튼도 키보드 위로 올라가도록 구현 
     : `android:windowSoftInputMode`
